// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthRedisRepository creates a new instance of MockAuthRedisRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthRedisRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthRedisRepository {
	mock := &MockAuthRedisRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthRedisRepository is an autogenerated mock type for the AuthRedisRepository type
type MockAuthRedisRepository struct {
	mock.Mock
}

type MockAuthRedisRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthRedisRepository) EXPECT() *MockAuthRedisRepository_Expecter {
	return &MockAuthRedisRepository_Expecter{mock: &_m.Mock}
}

// DeleteSession provides a mock function for the type MockAuthRedisRepository
func (_mock *MockAuthRedisRepository) DeleteSession(ctx context.Context, token string) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthRedisRepository_DeleteSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSession'
type MockAuthRedisRepository_DeleteSession_Call struct {
	*mock.Call
}

// DeleteSession is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockAuthRedisRepository_Expecter) DeleteSession(ctx any, token any) *MockAuthRedisRepository_DeleteSession_Call {
	return &MockAuthRedisRepository_DeleteSession_Call{Call: _e.mock.On("DeleteSession", ctx, token)}
}

func (_c *MockAuthRedisRepository_DeleteSession_Call) Run(run func(ctx context.Context, token string)) *MockAuthRedisRepository_DeleteSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthRedisRepository_DeleteSession_Call) Return(err error) *MockAuthRedisRepository_DeleteSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthRedisRepository_DeleteSession_Call) RunAndReturn(run func(ctx context.Context, token string) error) *MockAuthRedisRepository_DeleteSession_Call {
	_c.Call.Return(run)
	return _c
}

// SaveSession provides a mock function for the type MockAuthRedisRepository
func (_mock *MockAuthRedisRepository) SaveSession(ctx context.Context, token string, authData []byte, ttl time.Duration) error {
	ret := _mock.Called(ctx, token, authData, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SaveSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte, time.Duration) error); ok {
		r0 = returnFunc(ctx, token, authData, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthRedisRepository_SaveSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveSession'
type MockAuthRedisRepository_SaveSession_Call struct {
	*mock.Call
}

// SaveSession is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - authData []byte
//   - ttl time.Duration
func (_e *MockAuthRedisRepository_Expecter) SaveSession(ctx any, token any, authData any, ttl any) *MockAuthRedisRepository_SaveSession_Call {
	return &MockAuthRedisRepository_SaveSession_Call{Call: _e.mock.On("SaveSession", ctx, token, authData, ttl)}
}

func (_c *MockAuthRedisRepository_SaveSession_Call) Run(run func(ctx context.Context, token string, authData []byte, ttl time.Duration)) *MockAuthRedisRepository_SaveSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAuthRedisRepository_SaveSession_Call) Return(err error) *MockAuthRedisRepository_SaveSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthRedisRepository_SaveSession_Call) RunAndReturn(run func(ctx context.Context, token string, authData []byte, ttl time.Duration) error) *MockAuthRedisRepository_SaveSession_Call {
	_c.Call.Return(run)
	return _c
}

// SessionExists provides a mock function for the type MockAuthRedisRepository
func (_mock *MockAuthRedisRepository) SessionExists(ctx context.Context, token string) (bool, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for SessionExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthRedisRepository_SessionExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SessionExists'
type MockAuthRedisRepository_SessionExists_Call struct {
	*mock.Call
}

// SessionExists is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockAuthRedisRepository_Expecter) SessionExists(ctx any, token any) *MockAuthRedisRepository_SessionExists_Call {
	return &MockAuthRedisRepository_SessionExists_Call{Call: _e.mock.On("SessionExists", ctx, token)}
}

func (_c *MockAuthRedisRepository_SessionExists_Call) Run(run func(ctx context.Context, token string)) *MockAuthRedisRepository_SessionExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthRedisRepository_SessionExists_Call) Return(b bool, err error) *MockAuthRedisRepository_SessionExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockAuthRedisRepository_SessionExists_Call) RunAndReturn(run func(ctx context.Context, token string) (bool, error)) *MockAuthRedisRepository_SessionExists_Call {
	_c.Call.Return(run)
	return _c
}
