// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Mpayy/digital-wallet-api/internal/wallet/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockWalletProvisioner creates a new instance of MockWalletProvisioner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWalletProvisioner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWalletProvisioner {
	mock := &MockWalletProvisioner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWalletProvisioner is an autogenerated mock type for the WalletProvisioner type
type MockWalletProvisioner struct {
	mock.Mock
}

type MockWalletProvisioner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWalletProvisioner) EXPECT() *MockWalletProvisioner_Expecter {
	return &MockWalletProvisioner_Expecter{mock: &_m.Mock}
}

// CreateWallet provides a mock function for the type MockWalletProvisioner
func (_mock *MockWalletProvisioner) CreateWallet(ctx context.Context, userID uint) (*entity.Wallet, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateWallet")
	}

	var r0 *entity.Wallet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (*entity.Wallet, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) *entity.Wallet); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Wallet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWalletProvisioner_CreateWallet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWallet'
type MockWalletProvisioner_CreateWallet_Call struct {
	*mock.Call
}

// CreateWallet is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockWalletProvisioner_Expecter) CreateWallet(ctx any, userID any) *MockWalletProvisioner_CreateWallet_Call {
	return &MockWalletProvisioner_CreateWallet_Call{Call: _e.mock.On("CreateWallet", ctx, userID)}
}

func (_c *MockWalletProvisioner_CreateWallet_Call) Run(run func(ctx context.Context, userID uint)) *MockWalletProvisioner_CreateWallet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWalletProvisioner_CreateWallet_Call) Return(wallet *entity.Wallet, err error) *MockWalletProvisioner_CreateWallet_Call {
	_c.Call.Return(wallet, err)
	return _c
}

func (_c *MockWalletProvisioner_CreateWallet_Call) RunAndReturn(run func(ctx context.Context, userID uint) (*entity.Wallet, error)) *MockWalletProvisioner_CreateWallet_Call {
	_c.Call.Return(run)
	return _c
}
