services:
  app:
    build: .

    container_name: digital-wallet-api-app
    restart: unless-stopped
    
    ports:
      - "8080:8080"

    env_file:
      - .env

    environment:
      - DATABASE_HOST=postgres 
      - REDIS_HOST=redis
      - DATABASE_PASSWORD=postgres

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

    networks:
      - digital-wallet-api-network

  postgres:
    image: postgres:16-alpine

    container_name: digital-wallet-api-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres        
      POSTGRES_DB: digital_wallet_api        

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d digital_wallet_api"]
      interval: 5s
      timeout: 5s
      retries: 5

    networks:
      - digital-wallet-api-network
  
  redis:
    image: redis:7-alpine

    container_name: digital-wallet-api-redis

    restart: unless-stopped

    ports:
      - "6379:6379"

    command: redis-server --appendonly yes

    volumes:
      - redis_data:/data

    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 5s
      timeout: 5s
      retries: 5

    networks:
      - digital-wallet-api-network

volumes:
  postgres_data:
  redis_data:  

networks:
  digital-wallet-api-network:
    driver: bridge