services:
  mysql-test:
    image: mysql:8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: digital_wallet_test
    ports:
      - "3307:3306"
    tmpfs:
      - /var/lib/mysql