// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Mpayy/digital-wallet-api/internal/wallet/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewMockWalletTopUpper creates a new instance of MockWalletTopUpper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWalletTopUpper(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWalletTopUpper {
	mock := &MockWalletTopUpper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWalletTopUpper is an autogenerated mock type for the WalletTopUpper type
type MockWalletTopUpper struct {
	mock.Mock
}

type MockWalletTopUpper_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWalletTopUpper) EXPECT() *MockWalletTopUpper_Expecter {
	return &MockWalletTopUpper_Expecter{mock: &_m.Mock}
}

// TopUp provides a mock function for the type MockWalletTopUpper
func (_mock *MockWalletTopUpper) TopUp(ctx context.Context, userID uint, req dto.TopUpRequest, idemKey string) (*dto.TopUpResponse, error) {
	ret := _mock.Called(ctx, userID, req, idemKey)

	if len(ret) == 0 {
		panic("no return value specified for TopUp")
	}

	var r0 *dto.TopUpResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, dto.TopUpRequest, string) (*dto.TopUpResponse, error)); ok {
		return returnFunc(ctx, userID, req, idemKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, dto.TopUpRequest, string) *dto.TopUpResponse); ok {
		r0 = returnFunc(ctx, userID, req, idemKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TopUpResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, dto.TopUpRequest, string) error); ok {
		r1 = returnFunc(ctx, userID, req, idemKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWalletTopUpper_TopUp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TopUp'
type MockWalletTopUpper_TopUp_Call struct {
	*mock.Call
}

// TopUp is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - req dto.TopUpRequest
//   - idemKey string
func (_e *MockWalletTopUpper_Expecter) TopUp(ctx any, userID any, req any, idemKey any) *MockWalletTopUpper_TopUp_Call {
	return &MockWalletTopUpper_TopUp_Call{Call: _e.mock.On("TopUp", ctx, userID, req, idemKey)}
}

func (_c *MockWalletTopUpper_TopUp_Call) Run(run func(ctx context.Context, userID uint, req dto.TopUpRequest, idemKey string)) *MockWalletTopUpper_TopUp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 dto.TopUpRequest
		if args[2] != nil {
			arg2 = args[2].(dto.TopUpRequest)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockWalletTopUpper_TopUp_Call) Return(topUpResponse *dto.TopUpResponse, err error) *MockWalletTopUpper_TopUp_Call {
	_c.Call.Return(topUpResponse, err)
	return _c
}

func (_c *MockWalletTopUpper_TopUp_Call) RunAndReturn(run func(ctx context.Context, userID uint, req dto.TopUpRequest, idemKey string) (*dto.TopUpResponse, error)) *MockWalletTopUpper_TopUp_Call {
	_c.Call.Return(run)
	return _c
}
