// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Mpayy/digital-wallet-api/internal/payment/gateway"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPaymentCollector creates a new instance of MockPaymentCollector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentCollector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentCollector {
	mock := &MockPaymentCollector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPaymentCollector is an autogenerated mock type for the PaymentCollector type
type MockPaymentCollector struct {
	mock.Mock
}

type MockPaymentCollector_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentCollector) EXPECT() *MockPaymentCollector_Expecter {
	return &MockPaymentCollector_Expecter{mock: &_m.Mock}
}

// CreateCharge provides a mock function for the type MockPaymentCollector
func (_mock *MockPaymentCollector) CreateCharge(ctx context.Context, req gateway.ChargeRequest) (*gateway.ChargeResult, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateCharge")
	}

	var r0 *gateway.ChargeResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, gateway.ChargeRequest) (*gateway.ChargeResult, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, gateway.ChargeRequest) *gateway.ChargeResult); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gateway.ChargeResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, gateway.ChargeRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPaymentCollector_CreateCharge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCharge'
type MockPaymentCollector_CreateCharge_Call struct {
	*mock.Call
}

// CreateCharge is a helper method to define mock.On call
//   - ctx context.Context
//   - req gateway.ChargeRequest
func (_e *MockPaymentCollector_Expecter) CreateCharge(ctx any, req any) *MockPaymentCollector_CreateCharge_Call {
	return &MockPaymentCollector_CreateCharge_Call{Call: _e.mock.On("CreateCharge", ctx, req)}
}

func (_c *MockPaymentCollector_CreateCharge_Call) Run(run func(ctx context.Context, req gateway.ChargeRequest)) *MockPaymentCollector_CreateCharge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 gateway.ChargeRequest
		if args[1] != nil {
			arg1 = args[1].(gateway.ChargeRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPaymentCollector_CreateCharge_Call) Return(chargeResult *gateway.ChargeResult, err error) *MockPaymentCollector_CreateCharge_Call {
	_c.Call.Return(chargeResult, err)
	return _c
}

func (_c *MockPaymentCollector_CreateCharge_Call) RunAndReturn(run func(ctx context.Context, req gateway.ChargeRequest) (*gateway.ChargeResult, error)) *MockPaymentCollector_CreateCharge_Call {
	_c.Call.Return(run)
	return _c
}

// ParseWebhookPayload provides a mock function for the type MockPaymentCollector
func (_mock *MockPaymentCollector) ParseWebhookPayload(payload []byte) (*gateway.WebhookEvent, error) {
	ret := _mock.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for ParseWebhookPayload")
	}

	var r0 *gateway.WebhookEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (*gateway.WebhookEvent, error)); ok {
		return returnFunc(payload)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) *gateway.WebhookEvent); ok {
		r0 = returnFunc(payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gateway.WebhookEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(payload)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPaymentCollector_ParseWebhookPayload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseWebhookPayload'
type MockPaymentCollector_ParseWebhookPayload_Call struct {
	*mock.Call
}

// ParseWebhookPayload is a helper method to define mock.On call
//   - payload []byte
func (_e *MockPaymentCollector_Expecter) ParseWebhookPayload(payload any) *MockPaymentCollector_ParseWebhookPayload_Call {
	return &MockPaymentCollector_ParseWebhookPayload_Call{Call: _e.mock.On("ParseWebhookPayload", payload)}
}

func (_c *MockPaymentCollector_ParseWebhookPayload_Call) Run(run func(payload []byte)) *MockPaymentCollector_ParseWebhookPayload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPaymentCollector_ParseWebhookPayload_Call) Return(webhookEvent *gateway.WebhookEvent, err error) *MockPaymentCollector_ParseWebhookPayload_Call {
	_c.Call.Return(webhookEvent, err)
	return _c
}

func (_c *MockPaymentCollector_ParseWebhookPayload_Call) RunAndReturn(run func(payload []byte) (*gateway.WebhookEvent, error)) *MockPaymentCollector_ParseWebhookPayload_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyWebhookSignature provides a mock function for the type MockPaymentCollector
func (_mock *MockPaymentCollector) VerifyWebhookSignature(payload []byte) error {
	ret := _mock.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for VerifyWebhookSignature")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = returnFunc(payload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPaymentCollector_VerifyWebhookSignature_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyWebhookSignature'
type MockPaymentCollector_VerifyWebhookSignature_Call struct {
	*mock.Call
}

// VerifyWebhookSignature is a helper method to define mock.On call
//   - payload []byte
func (_e *MockPaymentCollector_Expecter) VerifyWebhookSignature(payload any) *MockPaymentCollector_VerifyWebhookSignature_Call {
	return &MockPaymentCollector_VerifyWebhookSignature_Call{Call: _e.mock.On("VerifyWebhookSignature", payload)}
}

func (_c *MockPaymentCollector_VerifyWebhookSignature_Call) Run(run func(payload []byte)) *MockPaymentCollector_VerifyWebhookSignature_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPaymentCollector_VerifyWebhookSignature_Call) Return(err error) *MockPaymentCollector_VerifyWebhookSignature_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPaymentCollector_VerifyWebhookSignature_Call) RunAndReturn(run func(payload []byte) error) *MockPaymentCollector_VerifyWebhookSignature_Call {
	_c.Call.Return(run)
	return _c
}
