// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIdempotencyClaimer creates a new instance of MockIdempotencyClaimer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIdempotencyClaimer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIdempotencyClaimer {
	mock := &MockIdempotencyClaimer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIdempotencyClaimer is an autogenerated mock type for the IdempotencyClaimer type
type MockIdempotencyClaimer struct {
	mock.Mock
}

type MockIdempotencyClaimer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIdempotencyClaimer) EXPECT() *MockIdempotencyClaimer_Expecter {
	return &MockIdempotencyClaimer_Expecter{mock: &_m.Mock}
}

// Claim provides a mock function for the type MockIdempotencyClaimer
func (_mock *MockIdempotencyClaimer) Claim(ctx context.Context, key string, userID uint, endpoint string, payload any) (bool, string, error) {
	ret := _mock.Called(ctx, key, userID, endpoint, payload)

	if len(ret) == 0 {
		panic("no return value specified for Claim")
	}

	var r0 bool
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint, string, any) (bool, string, error)); ok {
		return returnFunc(ctx, key, userID, endpoint, payload)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint, string, any) bool); ok {
		r0 = returnFunc(ctx, key, userID, endpoint, payload)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, uint, string, any) string); ok {
		r1 = returnFunc(ctx, key, userID, endpoint, payload)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, uint, string, any) error); ok {
		r2 = returnFunc(ctx, key, userID, endpoint, payload)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockIdempotencyClaimer_Claim_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Claim'
type MockIdempotencyClaimer_Claim_Call struct {
	*mock.Call
}

// Claim is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - userID uint
//   - endpoint string
//   - payload any
func (_e *MockIdempotencyClaimer_Expecter) Claim(ctx any, key any, userID any, endpoint any, payload any) *MockIdempotencyClaimer_Claim_Call {
	return &MockIdempotencyClaimer_Claim_Call{Call: _e.mock.On("Claim", ctx, key, userID, endpoint, payload)}
}

func (_c *MockIdempotencyClaimer_Claim_Call) Run(run func(ctx context.Context, key string, userID uint, endpoint string, payload any)) *MockIdempotencyClaimer_Claim_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 any
		if args[4] != nil {
			arg4 = args[4].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockIdempotencyClaimer_Claim_Call) Return(claimed bool, cachedBody string, err error) *MockIdempotencyClaimer_Claim_Call {
	_c.Call.Return(claimed, cachedBody, err)
	return _c
}

func (_c *MockIdempotencyClaimer_Claim_Call) RunAndReturn(run func(ctx context.Context, key string, userID uint, endpoint string, payload any) (bool, string, error)) *MockIdempotencyClaimer_Claim_Call {
	_c.Call.Return(run)
	return _c
}

// Complete provides a mock function for the type MockIdempotencyClaimer
func (_mock *MockIdempotencyClaimer) Complete(ctx context.Context, key string, response any) error {
	ret := _mock.Called(ctx, key, response)

	if len(ret) == 0 {
		panic("no return value specified for Complete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any) error); ok {
		r0 = returnFunc(ctx, key, response)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIdempotencyClaimer_Complete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Complete'
type MockIdempotencyClaimer_Complete_Call struct {
	*mock.Call
}

// Complete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - response any
func (_e *MockIdempotencyClaimer_Expecter) Complete(ctx any, key any, response any) *MockIdempotencyClaimer_Complete_Call {
	return &MockIdempotencyClaimer_Complete_Call{Call: _e.mock.On("Complete", ctx, key, response)}
}

func (_c *MockIdempotencyClaimer_Complete_Call) Run(run func(ctx context.Context, key string, response any)) *MockIdempotencyClaimer_Complete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIdempotencyClaimer_Complete_Call) Return(err error) *MockIdempotencyClaimer_Complete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIdempotencyClaimer_Complete_Call) RunAndReturn(run func(ctx context.Context, key string, response any) error) *MockIdempotencyClaimer_Complete_Call {
	_c.Call.Return(run)
	return _c
}

// MarkFailed provides a mock function for the type MockIdempotencyClaimer
func (_mock *MockIdempotencyClaimer) MarkFailed(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for MarkFailed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIdempotencyClaimer_MarkFailed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkFailed'
type MockIdempotencyClaimer_MarkFailed_Call struct {
	*mock.Call
}

// MarkFailed is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockIdempotencyClaimer_Expecter) MarkFailed(ctx any, key any) *MockIdempotencyClaimer_MarkFailed_Call {
	return &MockIdempotencyClaimer_MarkFailed_Call{Call: _e.mock.On("MarkFailed", ctx, key)}
}

func (_c *MockIdempotencyClaimer_MarkFailed_Call) Run(run func(ctx context.Context, key string)) *MockIdempotencyClaimer_MarkFailed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIdempotencyClaimer_MarkFailed_Call) Return(err error) *MockIdempotencyClaimer_MarkFailed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIdempotencyClaimer_MarkFailed_Call) RunAndReturn(run func(ctx context.Context, key string) error) *MockIdempotencyClaimer_MarkFailed_Call {
	_c.Call.Return(run)
	return _c
}
