// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Mpayy/digital-wallet-api/internal/payment/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPaymentRepository creates a new instance of MockPaymentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentRepository {
	mock := &MockPaymentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPaymentRepository is an autogenerated mock type for the PaymentRepository type
type MockPaymentRepository struct {
	mock.Mock
}

type MockPaymentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentRepository) EXPECT() *MockPaymentRepository_Expecter {
	return &MockPaymentRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockPaymentRepository
func (_mock *MockPaymentRepository) Create(ctx context.Context, payment *entity.PaymentTransaction) error {
	ret := _mock.Called(ctx, payment)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.PaymentTransaction) error); ok {
		r0 = returnFunc(ctx, payment)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPaymentRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPaymentRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - payment *entity.PaymentTransaction
func (_e *MockPaymentRepository_Expecter) Create(ctx any, payment any) *MockPaymentRepository_Create_Call {
	return &MockPaymentRepository_Create_Call{Call: _e.mock.On("Create", ctx, payment)}
}

func (_c *MockPaymentRepository_Create_Call) Run(run func(ctx context.Context, payment *entity.PaymentTransaction)) *MockPaymentRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.PaymentTransaction
		if args[1] != nil {
			arg1 = args[1].(*entity.PaymentTransaction)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPaymentRepository_Create_Call) Return(err error) *MockPaymentRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPaymentRepository_Create_Call) RunAndReturn(run func(ctx context.Context, payment *entity.PaymentTransaction) error) *MockPaymentRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByProviderRefID provides a mock function for the type MockPaymentRepository
func (_mock *MockPaymentRepository) FindByProviderRefID(ctx context.Context, provider string, providerRefID string) (*entity.PaymentTransaction, error) {
	ret := _mock.Called(ctx, provider, providerRefID)

	if len(ret) == 0 {
		panic("no return value specified for FindByProviderRefID")
	}

	var r0 *entity.PaymentTransaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*entity.PaymentTransaction, error)); ok {
		return returnFunc(ctx, provider, providerRefID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *entity.PaymentTransaction); ok {
		r0 = returnFunc(ctx, provider, providerRefID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.PaymentTransaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, provider, providerRefID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPaymentRepository_FindByProviderRefID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByProviderRefID'
type MockPaymentRepository_FindByProviderRefID_Call struct {
	*mock.Call
}

// FindByProviderRefID is a helper method to define mock.On call
//   - ctx context.Context
//   - provider string
//   - providerRefID string
func (_e *MockPaymentRepository_Expecter) FindByProviderRefID(ctx any, provider any, providerRefID any) *MockPaymentRepository_FindByProviderRefID_Call {
	return &MockPaymentRepository_FindByProviderRefID_Call{Call: _e.mock.On("FindByProviderRefID", ctx, provider, providerRefID)}
}

func (_c *MockPaymentRepository_FindByProviderRefID_Call) Run(run func(ctx context.Context, provider string, providerRefID string)) *MockPaymentRepository_FindByProviderRefID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPaymentRepository_FindByProviderRefID_Call) Return(paymentTransaction *entity.PaymentTransaction, err error) *MockPaymentRepository_FindByProviderRefID_Call {
	_c.Call.Return(paymentTransaction, err)
	return _c
}

func (_c *MockPaymentRepository_FindByProviderRefID_Call) RunAndReturn(run func(ctx context.Context, provider string, providerRefID string) (*entity.PaymentTransaction, error)) *MockPaymentRepository_FindByProviderRefID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type MockPaymentRepository
func (_mock *MockPaymentRepository) UpdateStatus(ctx context.Context, provider string, providerRefID string, status entity.PaymentTransactionStatus, walletTransactionID *uint, rawNotification *string) error {
	ret := _mock.Called(ctx, provider, providerRefID, status, walletTransactionID, rawNotification)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, entity.PaymentTransactionStatus, *uint, *string) error); ok {
		r0 = returnFunc(ctx, provider, providerRefID, status, walletTransactionID, rawNotification)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPaymentRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockPaymentRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - provider string
//   - providerRefID string
//   - status entity.PaymentTransactionStatus
//   - walletTransactionID *uint
//   - rawNotification *string
func (_e *MockPaymentRepository_Expecter) UpdateStatus(ctx any, provider any, providerRefID any, status any, walletTransactionID any, rawNotification any) *MockPaymentRepository_UpdateStatus_Call {
	return &MockPaymentRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, provider, providerRefID, status, walletTransactionID, rawNotification)}
}

func (_c *MockPaymentRepository_UpdateStatus_Call) Run(run func(ctx context.Context, provider string, providerRefID string, status entity.PaymentTransactionStatus, walletTransactionID *uint, rawNotification *string)) *MockPaymentRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 entity.PaymentTransactionStatus
		if args[3] != nil {
			arg3 = args[3].(entity.PaymentTransactionStatus)
		}
		var arg4 *uint
		if args[4] != nil {
			arg4 = args[4].(*uint)
		}
		var arg5 *string
		if args[5] != nil {
			arg5 = args[5].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockPaymentRepository_UpdateStatus_Call) Return(err error) *MockPaymentRepository_UpdateStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPaymentRepository_UpdateStatus_Call) RunAndReturn(run func(ctx context.Context, provider string, providerRefID string, status entity.PaymentTransactionStatus, walletTransactionID *uint, rawNotification *string) error) *MockPaymentRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}
