// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Mpayy/digital-wallet-api/internal/wallet/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewMockWalletWithdrawer creates a new instance of MockWalletWithdrawer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWalletWithdrawer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWalletWithdrawer {
	mock := &MockWalletWithdrawer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWalletWithdrawer is an autogenerated mock type for the WalletWithdrawer type
type MockWalletWithdrawer struct {
	mock.Mock
}

type MockWalletWithdrawer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWalletWithdrawer) EXPECT() *MockWalletWithdrawer_Expecter {
	return &MockWalletWithdrawer_Expecter{mock: &_m.Mock}
}

// FinalizeWithdrawal provides a mock function for the type MockWalletWithdrawer
func (_mock *MockWalletWithdrawer) FinalizeWithdrawal(ctx context.Context, transactionID uint) error {
	ret := _mock.Called(ctx, transactionID)

	if len(ret) == 0 {
		panic("no return value specified for FinalizeWithdrawal")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = returnFunc(ctx, transactionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWalletWithdrawer_FinalizeWithdrawal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FinalizeWithdrawal'
type MockWalletWithdrawer_FinalizeWithdrawal_Call struct {
	*mock.Call
}

// FinalizeWithdrawal is a helper method to define mock.On call
//   - ctx context.Context
//   - transactionID uint
func (_e *MockWalletWithdrawer_Expecter) FinalizeWithdrawal(ctx any, transactionID any) *MockWalletWithdrawer_FinalizeWithdrawal_Call {
	return &MockWalletWithdrawer_FinalizeWithdrawal_Call{Call: _e.mock.On("FinalizeWithdrawal", ctx, transactionID)}
}

func (_c *MockWalletWithdrawer_FinalizeWithdrawal_Call) Run(run func(ctx context.Context, transactionID uint)) *MockWalletWithdrawer_FinalizeWithdrawal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWalletWithdrawer_FinalizeWithdrawal_Call) Return(err error) *MockWalletWithdrawer_FinalizeWithdrawal_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWalletWithdrawer_FinalizeWithdrawal_Call) RunAndReturn(run func(ctx context.Context, transactionID uint) error) *MockWalletWithdrawer_FinalizeWithdrawal_Call {
	_c.Call.Return(run)
	return _c
}

// ReverseWithdrawal provides a mock function for the type MockWalletWithdrawer
func (_mock *MockWalletWithdrawer) ReverseWithdrawal(ctx context.Context, transactionID uint, reason string) error {
	ret := _mock.Called(ctx, transactionID, reason)

	if len(ret) == 0 {
		panic("no return value specified for ReverseWithdrawal")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string) error); ok {
		r0 = returnFunc(ctx, transactionID, reason)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWalletWithdrawer_ReverseWithdrawal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReverseWithdrawal'
type MockWalletWithdrawer_ReverseWithdrawal_Call struct {
	*mock.Call
}

// ReverseWithdrawal is a helper method to define mock.On call
//   - ctx context.Context
//   - transactionID uint
//   - reason string
func (_e *MockWalletWithdrawer_Expecter) ReverseWithdrawal(ctx any, transactionID any, reason any) *MockWalletWithdrawer_ReverseWithdrawal_Call {
	return &MockWalletWithdrawer_ReverseWithdrawal_Call{Call: _e.mock.On("ReverseWithdrawal", ctx, transactionID, reason)}
}

func (_c *MockWalletWithdrawer_ReverseWithdrawal_Call) Run(run func(ctx context.Context, transactionID uint, reason string)) *MockWalletWithdrawer_ReverseWithdrawal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWalletWithdrawer_ReverseWithdrawal_Call) Return(err error) *MockWalletWithdrawer_ReverseWithdrawal_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWalletWithdrawer_ReverseWithdrawal_Call) RunAndReturn(run func(ctx context.Context, transactionID uint, reason string) error) *MockWalletWithdrawer_ReverseWithdrawal_Call {
	_c.Call.Return(run)
	return _c
}

// Withdraw provides a mock function for the type MockWalletWithdrawer
func (_mock *MockWalletWithdrawer) Withdraw(ctx context.Context, userID uint, amount int64, idemKey string) (*dto.WithdrawResponse, error) {
	ret := _mock.Called(ctx, userID, amount, idemKey)

	if len(ret) == 0 {
		panic("no return value specified for Withdraw")
	}

	var r0 *dto.WithdrawResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, int64, string) (*dto.WithdrawResponse, error)); ok {
		return returnFunc(ctx, userID, amount, idemKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, int64, string) *dto.WithdrawResponse); ok {
		r0 = returnFunc(ctx, userID, amount, idemKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.WithdrawResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, int64, string) error); ok {
		r1 = returnFunc(ctx, userID, amount, idemKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWalletWithdrawer_Withdraw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Withdraw'
type MockWalletWithdrawer_Withdraw_Call struct {
	*mock.Call
}

// Withdraw is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - amount int64
//   - idemKey string
func (_e *MockWalletWithdrawer_Expecter) Withdraw(ctx any, userID any, amount any, idemKey any) *MockWalletWithdrawer_Withdraw_Call {
	return &MockWalletWithdrawer_Withdraw_Call{Call: _e.mock.On("Withdraw", ctx, userID, amount, idemKey)}
}

func (_c *MockWalletWithdrawer_Withdraw_Call) Run(run func(ctx context.Context, userID uint, amount int64, idemKey string)) *MockWalletWithdrawer_Withdraw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockWalletWithdrawer_Withdraw_Call) Return(withdrawResponse *dto.WithdrawResponse, err error) *MockWalletWithdrawer_Withdraw_Call {
	_c.Call.Return(withdrawResponse, err)
	return _c
}

func (_c *MockWalletWithdrawer_Withdraw_Call) RunAndReturn(run func(ctx context.Context, userID uint, amount int64, idemKey string) (*dto.WithdrawResponse, error)) *MockWalletWithdrawer_Withdraw_Call {
	_c.Call.Return(run)
	return _c
}
