// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"net/http"

	"github.com/Mpayy/digital-wallet-api/internal/payment/gateway"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPaymentDisburser creates a new instance of MockPaymentDisburser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentDisburser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentDisburser {
	mock := &MockPaymentDisburser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPaymentDisburser is an autogenerated mock type for the PaymentDisburser type
type MockPaymentDisburser struct {
	mock.Mock
}

type MockPaymentDisburser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentDisburser) EXPECT() *MockPaymentDisburser_Expecter {
	return &MockPaymentDisburser_Expecter{mock: &_m.Mock}
}

// CreatePayout provides a mock function for the type MockPaymentDisburser
func (_mock *MockPaymentDisburser) CreatePayout(ctx context.Context, req gateway.PayoutRequest) (*gateway.PayoutResult, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreatePayout")
	}

	var r0 *gateway.PayoutResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, gateway.PayoutRequest) (*gateway.PayoutResult, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, gateway.PayoutRequest) *gateway.PayoutResult); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gateway.PayoutResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, gateway.PayoutRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPaymentDisburser_CreatePayout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePayout'
type MockPaymentDisburser_CreatePayout_Call struct {
	*mock.Call
}

// CreatePayout is a helper method to define mock.On call
//   - ctx context.Context
//   - req gateway.PayoutRequest
func (_e *MockPaymentDisburser_Expecter) CreatePayout(ctx any, req any) *MockPaymentDisburser_CreatePayout_Call {
	return &MockPaymentDisburser_CreatePayout_Call{Call: _e.mock.On("CreatePayout", ctx, req)}
}

func (_c *MockPaymentDisburser_CreatePayout_Call) Run(run func(ctx context.Context, req gateway.PayoutRequest)) *MockPaymentDisburser_CreatePayout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 gateway.PayoutRequest
		if args[1] != nil {
			arg1 = args[1].(gateway.PayoutRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPaymentDisburser_CreatePayout_Call) Return(payoutResult *gateway.PayoutResult, err error) *MockPaymentDisburser_CreatePayout_Call {
	_c.Call.Return(payoutResult, err)
	return _c
}

func (_c *MockPaymentDisburser_CreatePayout_Call) RunAndReturn(run func(ctx context.Context, req gateway.PayoutRequest) (*gateway.PayoutResult, error)) *MockPaymentDisburser_CreatePayout_Call {
	_c.Call.Return(run)
	return _c
}

// ParsePayoutWebhook provides a mock function for the type MockPaymentDisburser
func (_mock *MockPaymentDisburser) ParsePayoutWebhook(payload []byte) (*gateway.PayoutWebhookEvent, error) {
	ret := _mock.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for ParsePayoutWebhook")
	}

	var r0 *gateway.PayoutWebhookEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (*gateway.PayoutWebhookEvent, error)); ok {
		return returnFunc(payload)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) *gateway.PayoutWebhookEvent); ok {
		r0 = returnFunc(payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gateway.PayoutWebhookEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(payload)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPaymentDisburser_ParsePayoutWebhook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParsePayoutWebhook'
type MockPaymentDisburser_ParsePayoutWebhook_Call struct {
	*mock.Call
}

// ParsePayoutWebhook is a helper method to define mock.On call
//   - payload []byte
func (_e *MockPaymentDisburser_Expecter) ParsePayoutWebhook(payload any) *MockPaymentDisburser_ParsePayoutWebhook_Call {
	return &MockPaymentDisburser_ParsePayoutWebhook_Call{Call: _e.mock.On("ParsePayoutWebhook", payload)}
}

func (_c *MockPaymentDisburser_ParsePayoutWebhook_Call) Run(run func(payload []byte)) *MockPaymentDisburser_ParsePayoutWebhook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPaymentDisburser_ParsePayoutWebhook_Call) Return(payoutWebhookEvent *gateway.PayoutWebhookEvent, err error) *MockPaymentDisburser_ParsePayoutWebhook_Call {
	_c.Call.Return(payoutWebhookEvent, err)
	return _c
}

func (_c *MockPaymentDisburser_ParsePayoutWebhook_Call) RunAndReturn(run func(payload []byte) (*gateway.PayoutWebhookEvent, error)) *MockPaymentDisburser_ParsePayoutWebhook_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyWebhookSignature provides a mock function for the type MockPaymentDisburser
func (_mock *MockPaymentDisburser) VerifyWebhookSignature(headers http.Header) error {
	ret := _mock.Called(headers)

	if len(ret) == 0 {
		panic("no return value specified for VerifyWebhookSignature")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(http.Header) error); ok {
		r0 = returnFunc(headers)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPaymentDisburser_VerifyWebhookSignature_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyWebhookSignature'
type MockPaymentDisburser_VerifyWebhookSignature_Call struct {
	*mock.Call
}

// VerifyWebhookSignature is a helper method to define mock.On call
//   - headers http.Header
func (_e *MockPaymentDisburser_Expecter) VerifyWebhookSignature(headers any) *MockPaymentDisburser_VerifyWebhookSignature_Call {
	return &MockPaymentDisburser_VerifyWebhookSignature_Call{Call: _e.mock.On("VerifyWebhookSignature", headers)}
}

func (_c *MockPaymentDisburser_VerifyWebhookSignature_Call) Run(run func(headers http.Header)) *MockPaymentDisburser_VerifyWebhookSignature_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.Header
		if args[0] != nil {
			arg0 = args[0].(http.Header)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPaymentDisburser_VerifyWebhookSignature_Call) Return(err error) *MockPaymentDisburser_VerifyWebhookSignature_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPaymentDisburser_VerifyWebhookSignature_Call) RunAndReturn(run func(headers http.Header) error) *MockPaymentDisburser_VerifyWebhookSignature_Call {
	_c.Call.Return(run)
	return _c
}
