// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Mpayy/digital-wallet-api/internal/config"
	"github.com/Mpayy/digital-wallet-api/internal/payment/gateway"
	"github.com/Mpayy/digital-wallet-api/internal/payment/repository"
	usecase2 "github.com/Mpayy/digital-wallet-api/internal/payment/usecase"
	"github.com/Mpayy/digital-wallet-api/internal/pkg/queue"
	repository2 "github.com/Mpayy/digital-wallet-api/internal/wallet/repository"
	"github.com/Mpayy/digital-wallet-api/internal/wallet/usecase"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeWorker() (*ApplicationWorker, func(), error) {
	viper := config.NewViper()
	logger := config.NewLogrus(viper)
	channel, cleanup, err := config.NewRabbitMQ(viper, logger)
	if err != nil {
		return nil, nil, err
	}
	db, cleanup2 := config.NewGorm(viper, logger)
	workerInfra := config.NewWorker(channel, logger, viper, db)
	consumer := queue.NewConsumer(channel, logger)
	paymentRepository := repository.NewPaymentRepository(db)
	paymentCollector := gateway.NewMidtransGateway(viper)
	walletRepository := repository2.NewWalletRepository(db)
	transactionRepository := repository2.NewTransactionRepository(db)
	idempotencyRepository := repository2.NewIdempotencyRepository(db)
	idempotencyService := usecase.NewIdempotencyService(logger, idempotencyRepository)
	walletUsecase := usecase.NewWalletUsecase(walletRepository, transactionRepository, idempotencyService, logger)
	publisher := queue.NewPublisher(channel, logger)
	paymentUsecase := usecase2.NewPaymentUsecase(paymentRepository, paymentCollector, walletUsecase, idempotencyService, logger, publisher)
	paymentDisburser := gateway.NewXenditGateway(viper)
	withdrawalUsecase := usecase2.NewWithdrawalUsecase(paymentRepository, paymentDisburser, walletUsecase, publisher, logger)
	worker := NewWorker(consumer, paymentUsecase, withdrawalUsecase)
	applicationWorker := NewApplicationWorker(workerInfra, worker)
	return applicationWorker, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

var infraSet = wire.NewSet(config.NewViper, config.NewLogrus, config.NewGorm, config.NewRabbitMQ, config.NewWorker)

var walletSet = wire.NewSet(repository2.NewWalletRepository, repository2.NewTransactionRepository, repository2.NewIdempotencyRepository, usecase.NewIdempotencyService, usecase.NewWalletUsecase, wire.Bind(new(usecase2.WalletTopUpper), new(usecase.WalletUsecase)), wire.Bind(new(usecase2.WalletWithdrawer), new(usecase.WalletUsecase)), wire.Bind(new(usecase2.IdempotencyClaimer), new(usecase.IdempotencyService)))

var paymentSet = wire.NewSet(repository.NewPaymentRepository, gateway.NewMidtransGateway, gateway.NewXenditGateway, usecase2.NewPaymentUsecase, usecase2.NewWithdrawalUsecase)

var pkgSet = wire.NewSet(queue.NewPublisher, queue.NewConsumer)
