// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Mpayy/digital-wallet-api/internal/config"
	"github.com/Mpayy/digital-wallet-api/internal/payment/gateway"
	"github.com/Mpayy/digital-wallet-api/internal/payment/repository"
	usecase2 "github.com/Mpayy/digital-wallet-api/internal/payment/usecase"
	"github.com/Mpayy/digital-wallet-api/internal/pkg/queue"
	repository2 "github.com/Mpayy/digital-wallet-api/internal/wallet/repository"
	"github.com/Mpayy/digital-wallet-api/internal/wallet/usecase"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeWorker() (*Worker, error) {
	viper := config.NewViper()
	channel, err := config.NewRabbitMQ(viper)
	if err != nil {
		return nil, err
	}
	logger := config.NewLogrus(viper)
	consumer := queue.NewConsumer(channel, logger)
	db := config.NewGorm(viper, logger)
	paymentRepository := repository.NewPaymentRepository(db)
	paymentCollector := gateway.NewMidtransGateway(viper)
	walletRepository := repository2.NewWalletRepository(db)
	transactionRepository := repository2.NewTransactionRepository(db)
	idempotencyRepository := repository2.NewIdempotencyRepository(db)
	idempotencyService := usecase.NewIdempotencyService(logger, idempotencyRepository)
	walletUsecase := usecase.NewWalletUsecase(walletRepository, transactionRepository, idempotencyService, logger)
	publisher := queue.NewPublisher(channel, logger)
	paymentUsecase := usecase2.NewPaymentUsecase(paymentRepository, paymentCollector, walletUsecase, idempotencyService, logger, publisher)
	worker := NewWorker(consumer, paymentUsecase)
	return worker, nil
}

// wire.go:

var infraSet = wire.NewSet(config.NewViper, config.NewLogrus, config.NewGorm, config.NewRabbitMQ)

var walletSet = wire.NewSet(repository2.NewWalletRepository, repository2.NewTransactionRepository, repository2.NewIdempotencyRepository, usecase.NewIdempotencyService, usecase.NewWalletUsecase, wire.Bind(new(usecase2.WalletTopUpper), new(usecase.WalletUsecase)), wire.Bind(new(usecase2.IdempotencyClaimer), new(usecase.IdempotencyService)))

var paymentSet = wire.NewSet(repository.NewPaymentRepository, gateway.NewMidtransGateway, usecase2.NewPaymentUsecase)

var pkgSet = wire.NewSet(queue.NewPublisher, queue.NewConsumer)
