// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Mpayy/digital-wallet-api/internal/wallet/dto"
	"github.com/Mpayy/digital-wallet-api/internal/wallet/entity"
	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockTransactionRepository creates a new instance of MockTransactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionRepository {
	mock := &MockTransactionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransactionRepository is an autogenerated mock type for the TransactionRepository type
type MockTransactionRepository struct {
	mock.Mock
}

type MockTransactionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionRepository) EXPECT() *MockTransactionRepository_Expecter {
	return &MockTransactionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockTransactionRepository
func (_mock *MockTransactionRepository) Create(tx *gorm.DB, transaction *entity.Transaction) error {
	ret := _mock.Called(tx, transaction)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB, *entity.Transaction) error); ok {
		r0 = returnFunc(tx, transaction)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTransactionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - tx *gorm.DB
//   - transaction *entity.Transaction
func (_e *MockTransactionRepository_Expecter) Create(tx any, transaction any) *MockTransactionRepository_Create_Call {
	return &MockTransactionRepository_Create_Call{Call: _e.mock.On("Create", tx, transaction)}
}

func (_c *MockTransactionRepository_Create_Call) Run(run func(tx *gorm.DB, transaction *entity.Transaction)) *MockTransactionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		var arg1 *entity.Transaction
		if args[1] != nil {
			arg1 = args[1].(*entity.Transaction)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionRepository_Create_Call) Return(err error) *MockTransactionRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactionRepository_Create_Call) RunAndReturn(run func(tx *gorm.DB, transaction *entity.Transaction) error) *MockTransactionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockTransactionRepository
func (_mock *MockTransactionRepository) FindByID(ctx context.Context, id uint) (*entity.Transaction, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (*entity.Transaction, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) *entity.Transaction); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockTransactionRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockTransactionRepository_Expecter) FindByID(ctx any, id any) *MockTransactionRepository_FindByID_Call {
	return &MockTransactionRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockTransactionRepository_FindByID_Call) Run(run func(ctx context.Context, id uint)) *MockTransactionRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionRepository_FindByID_Call) Return(transaction *entity.Transaction, err error) *MockTransactionRepository_FindByID_Call {
	_c.Call.Return(transaction, err)
	return _c
}

func (_c *MockTransactionRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id uint) (*entity.Transaction, error)) *MockTransactionRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByWalletID provides a mock function for the type MockTransactionRepository
func (_mock *MockTransactionRepository) FindByWalletID(ctx context.Context, walletID uint, filter dto.TransactionFilter) ([]entity.Transaction, int64, error) {
	ret := _mock.Called(ctx, walletID, filter)

	if len(ret) == 0 {
		panic("no return value specified for FindByWalletID")
	}

	var r0 []entity.Transaction
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, dto.TransactionFilter) ([]entity.Transaction, int64, error)); ok {
		return returnFunc(ctx, walletID, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, dto.TransactionFilter) []entity.Transaction); ok {
		r0 = returnFunc(ctx, walletID, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, dto.TransactionFilter) int64); ok {
		r1 = returnFunc(ctx, walletID, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uint, dto.TransactionFilter) error); ok {
		r2 = returnFunc(ctx, walletID, filter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockTransactionRepository_FindByWalletID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByWalletID'
type MockTransactionRepository_FindByWalletID_Call struct {
	*mock.Call
}

// FindByWalletID is a helper method to define mock.On call
//   - ctx context.Context
//   - walletID uint
//   - filter dto.TransactionFilter
func (_e *MockTransactionRepository_Expecter) FindByWalletID(ctx any, walletID any, filter any) *MockTransactionRepository_FindByWalletID_Call {
	return &MockTransactionRepository_FindByWalletID_Call{Call: _e.mock.On("FindByWalletID", ctx, walletID, filter)}
}

func (_c *MockTransactionRepository_FindByWalletID_Call) Run(run func(ctx context.Context, walletID uint, filter dto.TransactionFilter)) *MockTransactionRepository_FindByWalletID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 dto.TransactionFilter
		if args[2] != nil {
			arg2 = args[2].(dto.TransactionFilter)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTransactionRepository_FindByWalletID_Call) Return(transactions []entity.Transaction, n int64, err error) *MockTransactionRepository_FindByWalletID_Call {
	_c.Call.Return(transactions, n, err)
	return _c
}

func (_c *MockTransactionRepository_FindByWalletID_Call) RunAndReturn(run func(ctx context.Context, walletID uint, filter dto.TransactionFilter) ([]entity.Transaction, int64, error)) *MockTransactionRepository_FindByWalletID_Call {
	_c.Call.Return(run)
	return _c
}
