// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Mpayy/digital-wallet-api/internal/wallet/entity"
	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockWalletRepository creates a new instance of MockWalletRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWalletRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWalletRepository {
	mock := &MockWalletRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWalletRepository is an autogenerated mock type for the WalletRepository type
type MockWalletRepository struct {
	mock.Mock
}

type MockWalletRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWalletRepository) EXPECT() *MockWalletRepository_Expecter {
	return &MockWalletRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockWalletRepository
func (_mock *MockWalletRepository) Create(ctx context.Context, wallet *entity.Wallet) error {
	ret := _mock.Called(ctx, wallet)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Wallet) error); ok {
		r0 = returnFunc(ctx, wallet)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWalletRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockWalletRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - wallet *entity.Wallet
func (_e *MockWalletRepository_Expecter) Create(ctx any, wallet any) *MockWalletRepository_Create_Call {
	return &MockWalletRepository_Create_Call{Call: _e.mock.On("Create", ctx, wallet)}
}

func (_c *MockWalletRepository_Create_Call) Run(run func(ctx context.Context, wallet *entity.Wallet)) *MockWalletRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Wallet
		if args[1] != nil {
			arg1 = args[1].(*entity.Wallet)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWalletRepository_Create_Call) Return(err error) *MockWalletRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWalletRepository_Create_Call) RunAndReturn(run func(ctx context.Context, wallet *entity.Wallet) error) *MockWalletRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserID provides a mock function for the type MockWalletRepository
func (_mock *MockWalletRepository) FindByUserID(ctx context.Context, userID uint) (*entity.Wallet, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 *entity.Wallet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (*entity.Wallet, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) *entity.Wallet); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Wallet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWalletRepository_FindByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserID'
type MockWalletRepository_FindByUserID_Call struct {
	*mock.Call
}

// FindByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockWalletRepository_Expecter) FindByUserID(ctx any, userID any) *MockWalletRepository_FindByUserID_Call {
	return &MockWalletRepository_FindByUserID_Call{Call: _e.mock.On("FindByUserID", ctx, userID)}
}

func (_c *MockWalletRepository_FindByUserID_Call) Run(run func(ctx context.Context, userID uint)) *MockWalletRepository_FindByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWalletRepository_FindByUserID_Call) Return(wallet *entity.Wallet, err error) *MockWalletRepository_FindByUserID_Call {
	_c.Call.Return(wallet, err)
	return _c
}

func (_c *MockWalletRepository_FindByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uint) (*entity.Wallet, error)) *MockWalletRepository_FindByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// LockByID provides a mock function for the type MockWalletRepository
func (_mock *MockWalletRepository) LockByID(tx *gorm.DB, walletID uint) (*entity.Wallet, error) {
	ret := _mock.Called(tx, walletID)

	if len(ret) == 0 {
		panic("no return value specified for LockByID")
	}

	var r0 *entity.Wallet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB, uint) (*entity.Wallet, error)); ok {
		return returnFunc(tx, walletID)
	}
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB, uint) *entity.Wallet); ok {
		r0 = returnFunc(tx, walletID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Wallet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*gorm.DB, uint) error); ok {
		r1 = returnFunc(tx, walletID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWalletRepository_LockByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LockByID'
type MockWalletRepository_LockByID_Call struct {
	*mock.Call
}

// LockByID is a helper method to define mock.On call
//   - tx *gorm.DB
//   - walletID uint
func (_e *MockWalletRepository_Expecter) LockByID(tx any, walletID any) *MockWalletRepository_LockByID_Call {
	return &MockWalletRepository_LockByID_Call{Call: _e.mock.On("LockByID", tx, walletID)}
}

func (_c *MockWalletRepository_LockByID_Call) Run(run func(tx *gorm.DB, walletID uint)) *MockWalletRepository_LockByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWalletRepository_LockByID_Call) Return(wallet *entity.Wallet, err error) *MockWalletRepository_LockByID_Call {
	_c.Call.Return(wallet, err)
	return _c
}

func (_c *MockWalletRepository_LockByID_Call) RunAndReturn(run func(tx *gorm.DB, walletID uint) (*entity.Wallet, error)) *MockWalletRepository_LockByID_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockWalletRepository
func (_mock *MockWalletRepository) Save(tx *gorm.DB, wallet *entity.Wallet) error {
	ret := _mock.Called(tx, wallet)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB, *entity.Wallet) error); ok {
		r0 = returnFunc(tx, wallet)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWalletRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockWalletRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - tx *gorm.DB
//   - wallet *entity.Wallet
func (_e *MockWalletRepository_Expecter) Save(tx any, wallet any) *MockWalletRepository_Save_Call {
	return &MockWalletRepository_Save_Call{Call: _e.mock.On("Save", tx, wallet)}
}

func (_c *MockWalletRepository_Save_Call) Run(run func(tx *gorm.DB, wallet *entity.Wallet)) *MockWalletRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		var arg1 *entity.Wallet
		if args[1] != nil {
			arg1 = args[1].(*entity.Wallet)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWalletRepository_Save_Call) Return(err error) *MockWalletRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWalletRepository_Save_Call) RunAndReturn(run func(tx *gorm.DB, wallet *entity.Wallet) error) *MockWalletRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// WithTx provides a mock function for the type MockWalletRepository
func (_mock *MockWalletRepository) WithTx(ctx context.Context, fn func(tx *gorm.DB) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(tx *gorm.DB) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWalletRepository_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type MockWalletRepository_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(tx *gorm.DB) error
func (_e *MockWalletRepository_Expecter) WithTx(ctx any, fn any) *MockWalletRepository_WithTx_Call {
	return &MockWalletRepository_WithTx_Call{Call: _e.mock.On("WithTx", ctx, fn)}
}

func (_c *MockWalletRepository_WithTx_Call) Run(run func(ctx context.Context, fn func(tx *gorm.DB) error)) *MockWalletRepository_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(tx *gorm.DB) error
		if args[1] != nil {
			arg1 = args[1].(func(tx *gorm.DB) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWalletRepository_WithTx_Call) Return(err error) *MockWalletRepository_WithTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWalletRepository_WithTx_Call) RunAndReturn(run func(ctx context.Context, fn func(tx *gorm.DB) error) error) *MockWalletRepository_WithTx_Call {
	_c.Call.Return(run)
	return _c
}
