// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/Mpayy/digital-wallet-api/internal/wallet/entity"
	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockTransferRepository creates a new instance of MockTransferRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransferRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransferRepository {
	mock := &MockTransferRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransferRepository is an autogenerated mock type for the TransferRepository type
type MockTransferRepository struct {
	mock.Mock
}

type MockTransferRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransferRepository) EXPECT() *MockTransferRepository_Expecter {
	return &MockTransferRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockTransferRepository
func (_mock *MockTransferRepository) Create(tx *gorm.DB, transfer *entity.Transfer) error {
	ret := _mock.Called(tx, transfer)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB, *entity.Transfer) error); ok {
		r0 = returnFunc(tx, transfer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransferRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTransferRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - tx *gorm.DB
//   - transfer *entity.Transfer
func (_e *MockTransferRepository_Expecter) Create(tx any, transfer any) *MockTransferRepository_Create_Call {
	return &MockTransferRepository_Create_Call{Call: _e.mock.On("Create", tx, transfer)}
}

func (_c *MockTransferRepository_Create_Call) Run(run func(tx *gorm.DB, transfer *entity.Transfer)) *MockTransferRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		var arg1 *entity.Transfer
		if args[1] != nil {
			arg1 = args[1].(*entity.Transfer)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransferRepository_Create_Call) Return(err error) *MockTransferRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransferRepository_Create_Call) RunAndReturn(run func(tx *gorm.DB, transfer *entity.Transfer) error) *MockTransferRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}
