// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Mpayy/digital-wallet-api/internal/wallet/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIdempotencyRepository creates a new instance of MockIdempotencyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIdempotencyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIdempotencyRepository {
	mock := &MockIdempotencyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIdempotencyRepository is an autogenerated mock type for the IdempotencyRepository type
type MockIdempotencyRepository struct {
	mock.Mock
}

type MockIdempotencyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIdempotencyRepository) EXPECT() *MockIdempotencyRepository_Expecter {
	return &MockIdempotencyRepository_Expecter{mock: &_m.Mock}
}

// FindByKey provides a mock function for the type MockIdempotencyRepository
func (_mock *MockIdempotencyRepository) FindByKey(ctx context.Context, key string) (*entity.IdempotencyKey, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for FindByKey")
	}

	var r0 *entity.IdempotencyKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.IdempotencyKey, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.IdempotencyKey); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.IdempotencyKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIdempotencyRepository_FindByKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByKey'
type MockIdempotencyRepository_FindByKey_Call struct {
	*mock.Call
}

// FindByKey is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockIdempotencyRepository_Expecter) FindByKey(ctx any, key any) *MockIdempotencyRepository_FindByKey_Call {
	return &MockIdempotencyRepository_FindByKey_Call{Call: _e.mock.On("FindByKey", ctx, key)}
}

func (_c *MockIdempotencyRepository_FindByKey_Call) Run(run func(ctx context.Context, key string)) *MockIdempotencyRepository_FindByKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIdempotencyRepository_FindByKey_Call) Return(idempotencyKey *entity.IdempotencyKey, err error) *MockIdempotencyRepository_FindByKey_Call {
	_c.Call.Return(idempotencyKey, err)
	return _c
}

func (_c *MockIdempotencyRepository_FindByKey_Call) RunAndReturn(run func(ctx context.Context, key string) (*entity.IdempotencyKey, error)) *MockIdempotencyRepository_FindByKey_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockIdempotencyRepository
func (_mock *MockIdempotencyRepository) Insert(ctx context.Context, record *entity.IdempotencyKey) error {
	ret := _mock.Called(ctx, record)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.IdempotencyKey) error); ok {
		r0 = returnFunc(ctx, record)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIdempotencyRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockIdempotencyRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - record *entity.IdempotencyKey
func (_e *MockIdempotencyRepository_Expecter) Insert(ctx any, record any) *MockIdempotencyRepository_Insert_Call {
	return &MockIdempotencyRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, record)}
}

func (_c *MockIdempotencyRepository_Insert_Call) Run(run func(ctx context.Context, record *entity.IdempotencyKey)) *MockIdempotencyRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.IdempotencyKey
		if args[1] != nil {
			arg1 = args[1].(*entity.IdempotencyKey)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIdempotencyRepository_Insert_Call) Return(err error) *MockIdempotencyRepository_Insert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIdempotencyRepository_Insert_Call) RunAndReturn(run func(ctx context.Context, record *entity.IdempotencyKey) error) *MockIdempotencyRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type MockIdempotencyRepository
func (_mock *MockIdempotencyRepository) UpdateStatus(ctx context.Context, key string, status entity.IdempotencyStatus, responseStatus int, responseBody string) error {
	ret := _mock.Called(ctx, key, status, responseStatus, responseBody)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, entity.IdempotencyStatus, int, string) error); ok {
		r0 = returnFunc(ctx, key, status, responseStatus, responseBody)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIdempotencyRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockIdempotencyRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - status entity.IdempotencyStatus
//   - responseStatus int
//   - responseBody string
func (_e *MockIdempotencyRepository_Expecter) UpdateStatus(ctx any, key any, status any, responseStatus any, responseBody any) *MockIdempotencyRepository_UpdateStatus_Call {
	return &MockIdempotencyRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, key, status, responseStatus, responseBody)}
}

func (_c *MockIdempotencyRepository_UpdateStatus_Call) Run(run func(ctx context.Context, key string, status entity.IdempotencyStatus, responseStatus int, responseBody string)) *MockIdempotencyRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 entity.IdempotencyStatus
		if args[2] != nil {
			arg2 = args[2].(entity.IdempotencyStatus)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockIdempotencyRepository_UpdateStatus_Call) Return(err error) *MockIdempotencyRepository_UpdateStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIdempotencyRepository_UpdateStatus_Call) RunAndReturn(run func(ctx context.Context, key string, status entity.IdempotencyStatus, responseStatus int, responseBody string) error) *MockIdempotencyRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}
