// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Mpayy/digital-wallet-api/internal/auth/handler"
	"github.com/Mpayy/digital-wallet-api/internal/auth/middleware"
	"github.com/Mpayy/digital-wallet-api/internal/auth/repository"
	usecase2 "github.com/Mpayy/digital-wallet-api/internal/auth/usecase"
	"github.com/Mpayy/digital-wallet-api/internal/config"
	"github.com/Mpayy/digital-wallet-api/internal/pkg/jwt"
	middleware2 "github.com/Mpayy/digital-wallet-api/internal/pkg/middleware"
	"github.com/Mpayy/digital-wallet-api/internal/pkg/txmanager"
	repository2 "github.com/Mpayy/digital-wallet-api/internal/wallet/repository"
	"github.com/Mpayy/digital-wallet-api/internal/wallet/usecase"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeAPI() *Application {
	viper := config.NewViper()
	engine := config.NewGin(viper)
	logger := config.NewLogrus(viper)
	db := config.NewGorm(viper, logger)
	client := config.NewRedisClient(viper)
	app := config.NewApp(engine, logger, viper, db, client)
	authRepository := repository.NewAuthRepository(db)
	walletRepository := repository2.NewWalletRepository(db)
	walletUsecase := usecase.NewWalletUsecase(walletRepository, logger)
	jwtToken := jwt.NewJwtToken(viper)
	authUsecase := usecase2.NewAuthUsecase(authRepository, walletUsecase, client, jwtToken, logger)
	validate := config.NewValidator()
	authHandler := authhandler.NewAuthHandler(authUsecase, validate, logger)
	jwtMiddleware := middleware.NewJwtMiddleware(jwtToken, client)
	router := NewRouter(engine, logger, authHandler, jwtMiddleware)
	application := NewApplication(app, router)
	return application
}

// wire.go:

var authSet = wire.NewSet(repository.NewAuthRepository, usecase2.NewAuthUsecase, authhandler.NewAuthHandler)

var walletSet = wire.NewSet(repository2.NewWalletRepository, usecase.NewWalletUsecase)

var middlewareSet = wire.NewSet(middleware.NewJwtMiddleware, middleware2.LoggerMiddleware)

var infraSet = wire.NewSet(config.NewViper, config.NewValidator, config.NewRedisClient, config.NewLogrus, config.NewGorm, config.NewGin, config.NewApp)

var pkgSet = wire.NewSet(jwt.NewJwtToken, txmanager.NewTxManager)
