// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Mpayy/digital-wallet-api/internal/config"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeAPI() *Application {
	viper := config.NewViper()
	logger := config.NewLogrus(viper)
	engine := config.NewGin(viper, logger)
	db := config.NewGorm(viper, logger)
	client := config.NewRedisClient(viper)
	app := config.NewApp(engine, logger, viper, db, client)
	router := NewRouter(engine)
	application := NewApplication(app, router)
	return application
}

// wire.go:

var infraSet = wire.NewSet(config.NewViper, config.NewValidator, config.NewRedisClient, config.NewLogrus, config.NewGorm, config.NewGin, config.NewApp)
