// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Mpayy/digital-wallet-api/internal/auth/handler"
	"github.com/Mpayy/digital-wallet-api/internal/auth/middleware"
	"github.com/Mpayy/digital-wallet-api/internal/auth/repository"
	usecase2 "github.com/Mpayy/digital-wallet-api/internal/auth/usecase"
	"github.com/Mpayy/digital-wallet-api/internal/config"
	"github.com/Mpayy/digital-wallet-api/internal/pkg/jwt"
	middleware2 "github.com/Mpayy/digital-wallet-api/internal/pkg/middleware"
	"github.com/Mpayy/digital-wallet-api/internal/wallet/handler"
	repository2 "github.com/Mpayy/digital-wallet-api/internal/wallet/repository"
	"github.com/Mpayy/digital-wallet-api/internal/wallet/usecase"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeAPI() *Application {
	viper := config.NewViper()
	engine := config.NewGin(viper)
	logger := config.NewLogrus(viper)
	db := config.NewGorm(viper, logger)
	client := config.NewRedisClient(viper)
	app := config.NewApp(engine, logger, viper, db, client)
	authRepository := repository.NewAuthRepository(db)
	walletRepository := repository2.NewWalletRepository(db)
	transactionRepository := repository2.NewTransactionRepository(db)
	idempotencyRepository := repository2.NewIdempotencyRepository(db)
	idempotencyService := usecase.NewIdempotencyService(logger, idempotencyRepository)
	walletUsecase := usecase.NewWalletUsecase(walletRepository, transactionRepository, idempotencyService, logger)
	jwtToken := jwt.NewJwtToken(viper)
	authUsecase := usecase2.NewAuthUsecase(authRepository, walletUsecase, client, jwtToken, logger)
	validate := config.NewValidator()
	authHandler := authhandler.NewAuthHandler(authUsecase, validate, logger)
	transferRepository := repository2.NewTransferRepository(db)
	transferUsecase := usecase.NewTransferUsecase(transferRepository, walletRepository, idempotencyService, transactionRepository, logger)
	walletHandler := handler.NewWalletHandler(walletUsecase, transferUsecase, validate)
	transactionUsecase := usecase.NewTransactionUsecase(transactionRepository, walletUsecase, logger)
	transactionHandler := handler.NewTransactionHandler(transactionUsecase, validate)
	jwtMiddleware := middleware.NewJwtMiddleware(jwtToken, client, logger)
	router := NewRouter(engine, logger, authHandler, walletHandler, transactionHandler, jwtMiddleware)
	application := NewApplication(app, router)
	return application
}

// wire.go:

var authSet = wire.NewSet(repository.NewAuthRepository, usecase2.NewAuthUsecase, authhandler.NewAuthHandler)

var walletSet = wire.NewSet(repository2.NewWalletRepository, usecase.NewWalletUsecase, handler.NewWalletHandler)

var transactionSet = wire.NewSet(repository2.NewTransactionRepository, usecase.NewTransactionUsecase, handler.NewTransactionHandler)

var idempotencySet = wire.NewSet(repository2.NewIdempotencyRepository, usecase.NewIdempotencyService)

var transferSet = wire.NewSet(repository2.NewTransferRepository, usecase.NewTransferUsecase)

var middlewareSet = wire.NewSet(middleware.NewJwtMiddleware, middleware2.LoggerMiddleware)

var infraSet = wire.NewSet(config.NewViper, config.NewValidator, config.NewRedisClient, config.NewLogrus, config.NewGorm, config.NewGin, config.NewApp)

var pkgSet = wire.NewSet(jwt.NewJwtToken)
