// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockConsumer creates a new instance of MockConsumer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConsumer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConsumer {
	mock := &MockConsumer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConsumer is an autogenerated mock type for the Consumer type
type MockConsumer struct {
	mock.Mock
}

type MockConsumer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConsumer) EXPECT() *MockConsumer_Expecter {
	return &MockConsumer_Expecter{mock: &_m.Mock}
}

// Consume provides a mock function for the type MockConsumer
func (_mock *MockConsumer) Consume(ctx context.Context, queueName string, handler func(body []byte) error) error {
	ret := _mock.Called(ctx, queueName, handler)

	if len(ret) == 0 {
		panic("no return value specified for Consume")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, func(body []byte) error) error); ok {
		r0 = returnFunc(ctx, queueName, handler)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConsumer_Consume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Consume'
type MockConsumer_Consume_Call struct {
	*mock.Call
}

// Consume is a helper method to define mock.On call
//   - ctx context.Context
//   - queueName string
//   - handler func(body []byte) error
func (_e *MockConsumer_Expecter) Consume(ctx any, queueName any, handler any) *MockConsumer_Consume_Call {
	return &MockConsumer_Consume_Call{Call: _e.mock.On("Consume", ctx, queueName, handler)}
}

func (_c *MockConsumer_Consume_Call) Run(run func(ctx context.Context, queueName string, handler func(body []byte) error)) *MockConsumer_Consume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 func(body []byte) error
		if args[2] != nil {
			arg2 = args[2].(func(body []byte) error)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockConsumer_Consume_Call) Return(err error) *MockConsumer_Consume_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConsumer_Consume_Call) RunAndReturn(run func(ctx context.Context, queueName string, handler func(body []byte) error) error) *MockConsumer_Consume_Call {
	_c.Call.Return(run)
	return _c
}
