// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Authenticates a user with email and password, returns a JWT access token and creates a session in Redis.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Login payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_auth_dto.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_response.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_auth_dto.LoginResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "BAD_REQUEST atau VALIDATION_ERROR",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_response.ErrorResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_apperror.AppError"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "INVALID_CREDENTIALS",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_response.ErrorResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_apperror.AppError"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "INTERNAL_SERVER_ERROR",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_response.ErrorResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_apperror.AppError"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Revokes the current session by deleting it from Redis.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Logout",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_response.SuccessResponse"
                        }
                    },
                    "401": {
                        "description": "UNAUTHORIZED / INVALID_TOKEN / TOKEN_HAS_EXPIRED",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_response.ErrorResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_apperror.AppError"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "INTERNAL_SERVER_ERROR",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_response.ErrorResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_apperror.AppError"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Creates a new user account with a bcrypt-hashed password. Email must be unique.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "User payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_auth_dto.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_response.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_auth_dto.RegisterResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "BAD_REQUEST (malformed JSON) atau VALIDATION_ERROR (lihat field 'fields')",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_response.ErrorResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_apperror.AppError"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "409": {
                        "description": "EMAIL_ALREADY_EXISTS",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_response.ErrorResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_apperror.AppError"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "INTERNAL_SERVER_ERROR",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_response.ErrorResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_apperror.AppError"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/transactions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a paginated, filterable list of the authenticated user's wallet transactions.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transaction"
                ],
                "summary": "List transaction history",
                "parameters": [
                    {
                        "enum": [
                            "TOPUP",
                            "TRANSFER_IN",
                            "TRANSFER_OUT"
                        ],
                        "type": "string",
                        "description": "Filter by type",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start date (YYYY-MM-DD)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date (YYYY-MM-DD), defaults to today if start_date is set",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Items per page (max 100)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_response.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_wallet_dto.TransactionListResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "BAD_REQUEST / VALIDATION_ERROR",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_response.ErrorResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_apperror.AppError"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "UNAUTHORIZED / INVALID_TOKEN / TOKEN_HAS_EXPIRED",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_response.ErrorResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_apperror.AppError"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "INTERNAL_SERVER_ERROR",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_response.ErrorResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_apperror.AppError"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/transactions/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a single transaction. Returns 404 both when the transaction does not exist and when it belongs to another user, to avoid leaking existence.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transaction"
                ],
                "summary": "Get transaction detail",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Transaction ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_response.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_wallet_dto.TransactionResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "BAD_REQUEST",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_response.ErrorResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_apperror.AppError"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "UNAUTHORIZED / INVALID_TOKEN / TOKEN_HAS_EXPIRED",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_response.ErrorResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_apperror.AppError"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "TRANSACTION_NOT_FOUND",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_response.ErrorResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_apperror.AppError"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "INTERNAL_SERVER_ERROR",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_response.ErrorResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_apperror.AppError"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/wallets/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the balance and metadata of the authenticated user's wallet.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wallet"
                ],
                "summary": "Get my wallet",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_response.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_wallet_dto.WalletResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "UNAUTHORIZED / INVALID_TOKEN / TOKEN_HAS_EXPIRED",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_response.ErrorResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_apperror.AppError"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "INTERNAL_SERVER_ERROR",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_response.ErrorResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_apperror.AppError"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/wallets/top-up": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Adds balance to the authenticated user's wallet. Requires a client-generated Idempotency-Key to safely retry on network failure.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wallet"
                ],
                "summary": "Top up wallet balance",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Client-generated UUID v4, unique per logical operation",
                        "name": "Idempotency-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Top up payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_wallet_dto.TopUpRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_response.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_wallet_dto.TopUpResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "BAD_REQUEST / VALIDATION_ERROR / MISSING_IDEMPOTENCY_KEY / INVALID_AMOUNT",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_response.ErrorResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_apperror.AppError"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "UNAUTHORIZED / INVALID_TOKEN / TOKEN_HAS_EXPIRED",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_response.ErrorResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_apperror.AppError"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "WALLET_NOT_FOUND",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_response.ErrorResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_apperror.AppError"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "409": {
                        "description": "IDEMPOTENCY_KEY_CONFLICT / REQUEST_IN_PROGRESS",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_response.ErrorResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_apperror.AppError"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "422": {
                        "description": "PREVIOUS_ATTEMPT_FAILED",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_response.ErrorResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_apperror.AppError"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "INTERNAL_SERVER_ERROR",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_response.ErrorResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_apperror.AppError"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/wallets/transfer": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Moves balance to another user's wallet using ordered row locking to prevent deadlock, with idempotency key support for safe retry.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wallet"
                ],
                "summary": "Transfer balance to another user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Client-generated UUID v4, unique per logical operation",
                        "name": "Idempotency-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Transfer payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_wallet_dto.TransferRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_response.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_wallet_dto.TransferResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "BAD_REQUEST / VALIDATION_ERROR / MISSING_IDEMPOTENCY_KEY / INVALID_AMOUNT",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_response.ErrorResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_apperror.AppError"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "UNAUTHORIZED / INVALID_TOKEN / TOKEN_HAS_EXPIRED",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_response.ErrorResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_apperror.AppError"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "WALLET_NOT_FOUND / RECIPIENT_NOT_FOUND",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_response.ErrorResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_apperror.AppError"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "409": {
                        "description": "IDEMPOTENCY_KEY_CONFLICT / REQUEST_IN_PROGRESS",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_response.ErrorResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_apperror.AppError"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "422": {
                        "description": "INSUFFICIENT_BALANCE / SELF_TRANSFER_NOT_ALLOWED / PREVIOUS_ATTEMPT_FAILED",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_response.ErrorResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_apperror.AppError"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "INTERNAL_SERVER_ERROR",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_response.ErrorResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_pkg_apperror.AppError"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_Mpayy_digital-wallet-api_internal_auth_dto.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "maxLength": 150
                },
                "password": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 6
                }
            }
        },
        "github_com_Mpayy_digital-wallet-api_internal_auth_dto.LoginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "github_com_Mpayy_digital-wallet-api_internal_auth_dto.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "maxLength": 150
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3
                },
                "password": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 6
                }
            }
        },
        "github_com_Mpayy_digital-wallet-api_internal_auth_dto.RegisterResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "github_com_Mpayy_digital-wallet-api_internal_pkg_apperror.AppError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "fields": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_Mpayy_digital-wallet-api_internal_pkg_response.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {},
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "github_com_Mpayy_digital-wallet-api_internal_pkg_response.SuccessResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "github_com_Mpayy_digital-wallet-api_internal_wallet_dto.MetaPagination": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "github_com_Mpayy_digital-wallet-api_internal_wallet_dto.TopUpRequest": {
            "type": "object",
            "required": [
                "amount"
            ],
            "properties": {
                "amount": {
                    "type": "integer"
                }
            }
        },
        "github_com_Mpayy_digital-wallet-api_internal_wallet_dto.TopUpResponse": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "balance_after": {
                    "type": "integer"
                },
                "balance_before": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "transaction_id": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                },
                "wallet_id": {
                    "type": "integer"
                }
            }
        },
        "github_com_Mpayy_digital-wallet-api_internal_wallet_dto.TransactionListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_wallet_dto.TransactionResponse"
                    }
                },
                "meta": {
                    "$ref": "#/definitions/github_com_Mpayy_digital-wallet-api_internal_wallet_dto.MetaPagination"
                }
            }
        },
        "github_com_Mpayy_digital-wallet-api_internal_wallet_dto.TransactionResponse": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "balance_after": {
                    "type": "integer"
                },
                "balance_before": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "transaction_id": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "github_com_Mpayy_digital-wallet-api_internal_wallet_dto.TransferRequest": {
            "type": "object",
            "required": [
                "amount",
                "to_user_id"
            ],
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "note": {
                    "type": "string",
                    "maxLength": 255
                },
                "to_user_id": {
                    "type": "integer"
                }
            }
        },
        "github_com_Mpayy_digital-wallet-api_internal_wallet_dto.TransferResponse": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "balance_after": {
                    "type": "integer"
                },
                "balance_before": {
                    "type": "integer"
                },
                "counterparty_user_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "transaction_id": {
                    "type": "integer"
                },
                "transfer_id": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "github_com_Mpayy_digital-wallet-api_internal_wallet_dto.WalletResponse": {
            "type": "object",
            "properties": {
                "balance": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Digital Wallet API",
	Description:      "Digital wallet built with Go, Gin, GORM, and Redis.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
