name: Integration Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Integration-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: digital_wallet_test
        ports:
          - 5432:5432
        options: >-
          --mount type=tmpfs,destination=/var/lib/postgresql/data
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26'

      - name: Install golang-migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.18.2/migrate.linux-amd64.tar.gz | tar xz
          sudo mv migrate /usr/local/bin/
      
      - name: Wait for postgres ready
        run: |
          for i in {1..10}; do
            pg_isready -h 127.0.0.1 -p 5432 -U postgres --q && break
            sleep 2
          done

      - name: Run migration
        run: migrate -path migrations -database "postgres://postgres:postgres@127.0.0.1:5432/digital_wallet_test?sslmode=disable&x-multi-statement=true" up

      - name: Run integration test
        run: go test -tags=integration -race ./test/integration/... -v
        env:
          TEST_DB_DSN: "host=127.0.0.1 user=postgres password=postgres dbname=digital_wallet_test port=5432 sslmode=disable"